### ISSUE TITLE
Apache APISIX API Traffic Management

### ISSUE THREAD

**Issue by kinlane** [postman-open-technologies/api-gateways#19]
Can we get the Apache APISIX API Traffic Management profiled, with their platform and gateway capabilities cataloged? https://apisix.apache.org/

**Comment by juzhiyuan** [comment]
Wow! Glad to see this issue 😊 @kinlane feel free to contact me if you need more information.

**Comment by kinlane** [comment]
Rating - 2

URL - https://apisix.apache.org/

- Load Balancing
- Dynamic Upstream
- Canary Release
- Circuit Breaking
- Authentication
- Observability
- Ingress Controller
- Dashboards
- High Performance
- Kubernetes
- Containers
- Docker
- OpenAPI
- Declarative
- Service Discovery
- Health Check
- Plugins
- Cloud
- On-Premise
- Load Balancing
- Open Source
- Cloud-Native
- TCP
- UDP
- Proxy
- MQTT
- gRPC
- HTTP
- SSL
- Websocket
- Traffic Split
- Proxy Mirror
- Response Rewrite
- JWT
- Basic Auth
- White List
- Black List
- Logging
- WASM
- RPC
